# -*- coding: utf-8 -*-
"""Fin Summer project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1emJRqobhVzm9csYj6XqWIwRQoDdKY9u5
"""

!pip install yfinance

!pip install nselib

import yfinance as yf
import pandas as pd
from nselib import capital_market
import time

portfolio_base = [
    "ADANIPOWER.NS", "TATAPOWER.NS", "BHARTIARTL.NS", "IDEA.NS",
    "CIPLA.NS", "SUNPHARMA.NS", "SBIN.NS", "BANKBARODA.NS",
    "INFY.NS", "WIPRO.NS", "JINDALSTEL.NS", "COALINDIA.NS"
]

indices = [
    "Nifty 50",
    "Nifty Smallcap 100",
    "Nifty500 Value 50",
    "Nifty 500 Growth 50"
    "Nifty 200 Momentum 30"
]

start_date = "2019-12-01"
end_date = "2022-01-01"

# Download the data
data = yf.download(portfolio_base, start=start_date, end=end_date)

adj_close_data = data["Close"]

# Display the first few rows of the data
print(adj_close_data.head())

# Optional: Save the data to a CSV file in your environment
adj_close_data.to_csv("stock_data_2019_2021.csv")

for index_name in indices:
    print(f"Fetching data for {index_name}...")
    try:
        # Pull the historical data
        df = capital_market.index_data(index=index_name, from_date=start_date, to_date=end_date)

        # Clean column names (strip trailing/leading spaces and make it case-insensitive for checking)
        df.columns = [col.strip() for col in df.columns]

        # Find the correct date column dynamically
        date_col = None
        for col in ['Date', 'TIMESTAMP', 'Date Of Current Day', 'Trading Date']:
            if col in df.columns:
                date_col = col
                break

        if date_col is None:
            raise KeyError(f"Could not find a recognized date column. Available columns: {list(df.columns)}")

        # Convert the identified date column to datetime
        # nselib usually returns standard string dates; errors='coerce' prevents code from breaking on bad rows
        df[date_col] = pd.to_datetime(df[date_col], errors='coerce')

        # Drop rows where the date conversion failed
        df.dropna(subset=[date_col], inplace=True)

        # Set index and sort
        df.set_index(date_col, inplace=True)
        df.index.name = 'Date'  # Standardize the index name
        df.sort_index(inplace=True)

        # Store in our dictionary
        historical_data[index_name] = df
        print(f"Successfully fetched {len(df)} trading days for {index_name}.\n")

        # Pause briefly to avoid hammering the server
        time.sleep(2)

    except Exception as e:
        print(f"Could not fetch {index_name}. Error: {e}\n")